// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package session

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionID struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionID(buf []byte, offset flatbuffers.UOffsetT) *SessionID {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionID{}
	x.Init(buf, n+offset)
	return x
}

func FinishSessionIDBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsSessionID(buf []byte, offset flatbuffers.UOffsetT) *SessionID {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionID{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedSessionIDBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *SessionID) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionID) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionID) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SessionIDStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SessionIDAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func SessionIDEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
